name: Push-to-EC2

on:
  push:
    branches:
      - main  # Only triggers on push to the main branch

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          ARGS: 
            --exclude='.gitignore'
            --exclude='.github/'
            --exclude='README.md'
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: "/var/www/html"

      - name: Build Vue Project
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER}}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                  cd /var/www/html/vue-project
                  sudo npm install
                  sudo npm run build